#!/bin/bash

# stop compose
docker-compose down

# remove all containers
docker rm $(docker ps -qa --filter="name=ruby_dev")

# remove all volumes
docker volume rm $(docker volume ls --filter="name=ruby_dev" -q)

# remove any network
docker network rm $(docker network ls -q --filter="name=ruby_dev")

# remove any images generated by us
docker rmi $(docker images -q --filter="reference=ruby_dev*")